name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Install Dependencies and Build Web
        run: |
          npm install
          npm run build

      - name: Install Capacitor
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Sync Capacitor with Android
        run: |
          rm -rf android
          npx cap add android
          npx cap sync android

      - name: Force Landscape & Fullscreen Orientation
        run: |
          # Deixa o app deitado
          sed -i 's/android:name=".MainActivity"/android:name=".MainActivity" android:screenOrientation="landscape"/' android/app/src/main/AndroidManifest.xml
          
          # Injeta a regra de Tela Cheia (Fullscreen)
          sed -i '/<style name="AppTheme.NoActionBar"/a\        <item name="android:windowFullscreen">true</item>' android/app/src/main/res/values/styles.xml
          sed -i '/<style name="AppTheme.NoActionBarLaunch"/a\        <item name="android:windowFullscreen">true</item>' android/app/src/main/res/values/styles.xml
          
          # Injeta a regra para o jogo invadir a area do Notch (Câmera) e tirar a borda lateral
          sed -i '/<style name="AppTheme.NoActionBar"/a\        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>' android/app/src/main/res/values/styles.xml
          sed -i '/<style name="AppTheme.NoActionBarLaunch"/a\        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>' android/app/src/main/res/values/styles.xml

      - name: Grant Execute Permission to Gradle
        run: chmod +x ./android/gradlew

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: polyshooter-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
